config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates:
      branch: main
      repo: https://gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-brown-spoonbill.sh
        container: qc.acc_stinky-turquoise-kangaroo
  QC.Doc:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-champagne-tuatara.sh
        container: qc.doc_cozy-tan-kudu
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-blue-squid.sh
        container: qc.doc_wheezy-denim-heron
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-aquamarine-orangutan.sh
        container: qc.doc_fuzzy-auburn-boar
  QC.Lic:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-khaki-zebra.sh
        container: qc.lic_boozy-ultramarine-weasel
  QC.Sty:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-burgundy-manatee.sh
        container: qc.sty_squirrely-rose-chameleon
  QC.Ver:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-grey-dingo.sh
        container: qc.ver_whiny-amber-barracuda
timeout: 5400
