config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates:
      branch: main
      repo: https://gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-malachite-kakapo.sh
        container: qc.acc_homely-peach-leopard
  QC.Doc:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-buff-heron.sh
        container: qc.doc_lousy-cinnamon-shark
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-eggplant-drever.sh
        container: qc.doc_squeaky-peach-panda
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-orange-toad.sh
        container: qc.doc_sleepy-aquamarine-llama
  QC.Lic:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-champagne-zonkey.sh
        container: qc.lic_snoopy-vermilion-oriole
  QC.Sty:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-puce-dugong.sh
        container: qc.sty_chummy-russet-opossum
  QC.Ver:
    repos:
      gitlab.a.incd.pt/envri-hub-next/analytical-workflow-templates get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lime-kakapo.sh
        container: qc.ver_snoopy-aquamarine-bracke
timeout: 5400
